### ISSUE TITLE
[BUG] Type Error with default fields

### ISSUE THREAD

**Issue by RFS-ADRENO** [Amrakk/mongooat#7]
**Describe the bug**
Inserting new data without the fields that have default values can result in a type error.

![image](https://github.com/user-attachments/assets/be1df930-edc5-4dc8-8af5-adc6aa924577)

**To Reproduce**
```ts
import { z, Mongooat } from "mongooat";

const mongooat = new Mongooat("url");
const UserSchema = z.object({
    name: z.string(),
    data: z.array(z.number()).default([]),
});

const userModel = mongooat.Model("users", UserSchema);

// Type error here
userModel
    .insertOne({
        name: "Dung", 
    })
    .catch(console.error);

```

### Expected behavior
For fields that have default values in an object, the model should not face any type-related issues during data insertion, even if those fields are excluded.

**Additional context**
None

**Comment by Amrakk** [comment]
- Fixed with: #10
