### ISSUE TITLE
[BUG] Type Error: Missing _id field

### ISSUE THREAD

**Issue by RFS-ADRENO** [Amrakk/mongooat#9]
**Describe the bug**
Missing _id field in the document type, although the _id field exists.

* Actual data:

![image](https://github.com/user-attachments/assets/f301c270-4dee-49bc-8d94-b85f663166d0)

* When trying to access _id field:

![image](https://github.com/user-attachments/assets/6bb16b09-2b3f-43d3-bb96-c4e565bab56f)

**To Reproduce**
```ts
import { z, Mongooat } from "mongooat";

const mongooat = new Mongooat("url");

const UserSchema = z.object({
    name: z.string(),
});

const userModel = mongooat.Model("users", UserSchema);

await userModel
    .insertOne({
        name: "Dung2",
    })
    .catch(console.error);

const getUser = await userModel.findOne({ name: "Dung2" }).catch((e) => {
    console.error(e);
    return null;
});

if (getUser) {
    const _id = getUser._id; // type error
    console.log(getUser);
}

```

### Expected behavior

The _id field should exist in the document type.

**Additional context**
None

**Comment by Amrakk** [comment]
- Fixed with #10
